/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class Radio extends javax.swing.JFrame {

    /**
     * Creates new form Radio
     */
    public Radio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Emisora1 = new javax.swing.JButton();
        Emisora2 = new javax.swing.JButton();
        Emisora3 = new javax.swing.JButton();
        Emisora4 = new javax.swing.JButton();
        Emisora5 = new javax.swing.JButton();
        Emisora6 = new javax.swing.JButton();
        Emisora7 = new javax.swing.JButton();
        Emisora8 = new javax.swing.JButton();
        Emisora9 = new javax.swing.JButton();
        Emisora10 = new javax.swing.JButton();
        Emisora11 = new javax.swing.JButton();
        Emisora12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("106.5");

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Emisora1.setText("1");
        Emisora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora1ActionPerformed(evt);
            }
        });

        Emisora2.setText("2");
        Emisora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora2ActionPerformed(evt);
            }
        });

        Emisora3.setText("3");
        Emisora3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora3ActionPerformed(evt);
            }
        });

        Emisora4.setText("4");
        Emisora4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora4ActionPerformed(evt);
            }
        });

        Emisora5.setText("5");
        Emisora5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora5ActionPerformed(evt);
            }
        });

        Emisora6.setText("6");
        Emisora6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora6ActionPerformed(evt);
            }
        });

        Emisora7.setText("7");
        Emisora7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora7ActionPerformed(evt);
            }
        });

        Emisora8.setText("8");
        Emisora8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora8ActionPerformed(evt);
            }
        });

        Emisora9.setText("9");
        Emisora9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora9ActionPerformed(evt);
            }
        });

        Emisora10.setText("10");
        Emisora10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora10ActionPerformed(evt);
            }
        });

        Emisora11.setText("11");
        Emisora11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora11ActionPerformed(evt);
            }
        });

        Emisora12.setText("12");
        Emisora12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emisora12ActionPerformed(evt);
            }
        });

        jButton4.setText("Switch");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("FM");

        jButton3.setText("ON");

        jButton5.setText("Set");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Emisora1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Emisora7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Emisora8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Emisora2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Emisora3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Emisora9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Emisora10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Emisora4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Emisora11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Emisora12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Emisora5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Emisora6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(82, 82, 82)
                                .addComponent(jButton1)))
                        .addGap(143, 610, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emisora1)
                    .addComponent(Emisora2)
                    .addComponent(Emisora3)
                    .addComponent(Emisora4)
                    .addComponent(Emisora5)
                    .addComponent(Emisora6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emisora7)
                    .addComponent(Emisora8)
                    .addComponent(Emisora9)
                    .addComponent(Emisora10)
                    .addComponent(Emisora11)
                    .addComponent(Emisora12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(459, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Emisora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora1ActionPerformed

    private void Emisora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora2ActionPerformed

    private void Emisora3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora3ActionPerformed

    private void Emisora4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora4ActionPerformed

    private void Emisora5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora5ActionPerformed

    private void Emisora6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora6ActionPerformed

    private void Emisora7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora7ActionPerformed

    private void Emisora8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora8ActionPerformed

    private void Emisora9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora9ActionPerformed

    private void Emisora10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora10ActionPerformed

    private void Emisora11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora11ActionPerformed

    private void Emisora12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emisora12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emisora12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Radio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Emisora1;
    private javax.swing.JButton Emisora10;
    private javax.swing.JButton Emisora11;
    private javax.swing.JButton Emisora12;
    private javax.swing.JButton Emisora2;
    private javax.swing.JButton Emisora3;
    private javax.swing.JButton Emisora4;
    private javax.swing.JButton Emisora5;
    private javax.swing.JButton Emisora6;
    private javax.swing.JButton Emisora7;
    private javax.swing.JButton Emisora8;
    private javax.swing.JButton Emisora9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
